<!DOCTYPE html>
<head>
  <?php include("includes/head.inc.html"); ?>
</head>

<body>
  <div class="cFull">
    <!-- header -->
    <?php include("includes/header.inc.php"); ?>

    <section class="section terminos">
      <div class="terminos__title">
        <div class="container">
          <h3>
            Términos y Condiciones
          </h2>
        </div>
      </div>

      <div class="terminos__text">
        <div class="container">
          <p><strong>Términos y condiciones de uso de Spiral</strong><br /><br />Los presentes Términos y Condiciones de Uso (en adelante las "Condiciones") regulan el uso del Sitio de titularidad de SPIRAL PLATFORM S.A.S. (en adelante "SPIRAL").<br /><br />Leer cuidadosamente estas Condiciones antes de utilizar el Sitio y/o la Plataforma de modo tal que Ud. ("Ud.", "su" o el "Usuario" y/o "Visitante", como corresponda) esté al tanto de sus derechos y obligaciones legales con respecto a SPIRAL.<br /><br />Nos reservamos el derecho, a nuestra única y entera discreción, de modificar estas Condiciones. Nosotros le informaremos a Ud. respecto de tales modificaciones ya sea por vía de su dirección de correo electrónico o publicando los cambios antes mencionados en el Sitio mismo y/o en la Plataforma. Deberá continuar controlando el Sitio y/o la Plataforma para estar al tanto de los cambios. Si continúa utilizando el Sitio y/o la Plataforma luego de transcurridos diez (10) días después de que hayamos publicado los cambios a estas Condiciones o después de que le hayamos avisado por correo electrónico, según lo primero que ocurra, eso se interpretará como que Ud. acepta dichos cambios.<br /><br /><strong>1. Consideraciones previas. Aceptación.<br /><br /></strong>1.1. Estas Condiciones constituyen un contrato entre Ud., ya sea personalmente o en nombre de una entidad o persona jurídica que Ud. representa, y SPIRAL, en relación con su acceso y uso del Sitio y de la Plataforma, así como en relación con su acceso y uso de cualquier otro medio de comunicación o canal de comunicación relacionado al Sitio. El Sitio proporciona acceso a una plataforma de almacenamiento y procesamiento de información online, propiedad de SPIRAL, que permite a los Usuarios controlar, gestionar y administrar ciertas funciones de sus cuentas de usuario en Mercadolibre® en los sitios www.mercadolibre.com y www.mercadopago.com (en adelante, la "Plataforma"). Estas Condiciones son aplicables al Sitio y a la Plataforma. Los derechos, obligaciones, responsabilidades, esquemas de precios y otros términos y condiciones suplementarios, o documentos que sean publicados en el Sitio y/o en la Plataforma en el futuro se incorporan expresamente a estas Condiciones.<br /></p>
          <p>1.2. Si Usted utiliza la Plataforma o el Sitio en nombre de una persona de existencia ideal, Usted afirma y garantiza a SPIRAL que se encuentra autorizado por dicha entidad para actuar a su nombre, bajo los términos de estas Condiciones.<br /><br /></p>
          <p>1.3. Concepto de Usuario y de Visitante. Si Ud. utiliza o visita de cualquier forma el Sitio y/o la Plataforma, independientemente de si está o no registrado como usuario del Sitio y/o de la Plataforma, Ud. es considerado un Visitante a los efectos de estas Condiciones. Si Ud. conecta su cuenta de usuario de MercadoLibre® a la Plataforma, se verifica vuestra registración para utilizar la Plataforma y Ud. es considerado un Usuario, a los efectos de estas Condiciones.<br /><br /></p>
          <p>1.4. Aplicación de las Condiciones. Aceptación. Mediante el uso (en su carácter de Usuario) o visitando (en su carácter de Visitante) del Sitio y/o de la Plataforma, Ud. acepta expresamente: (1) estas Condiciones y (2) la Política de Privacidad de SPIRAL, en www.DOMINIO/politicas-de-privacidad ("Política de Privacidad"), y las modificaciones de estas Condiciones y de la Política de Privacidad que SPIRAL pueda hacer en el futuro. Usted acepta expresamente estas Condiciones, reconociendo como válida la aceptación online. Estas Condiciones se aplicarán a todos los Usuarios y Visitantes del Sitio y/o de la Plataforma. Si Ud. no está de acuerdo con estas Condiciones o con la Política de Privacidad, no acceda ni utilice de cualquier forma el Sitio ni la Plataforma en modo alguno.<br /><br /></p>
          <p><strong>2. Capacidad para aceptar las Condiciones.<br /></strong><br/></p>
          <p>Si Ud. utiliza el Sitio y/o la Plataforma en nombre de una entidad de existencia ideal, usted afirma y garantiza que tiene las facultades o las autorizaciones necesarias para actuar en nombre y representación de dicha entidad.<br /><br /></p>
          <p><strong>3. Descripción de la Plataforma.<br /></strong><br/></p>
          <p>La Plataforma brinda al Usuario diversas herramientas que tienen por objetivo facilitarle el control y la administración de su cuenta de usuario en Mercadolibre® de acuerdo a lo explicado en estas Condiciones. En particular, la Plataforma brinda, clasifica y ordena información pública y privada del Usuario en Mercadolibre® y otorga herramientas que permiten al Usuario controlar, gestionar y administrar ciertas funciones de su cuenta de usuario en Mercadolibre®, incluyendo sin limitación las ventas concretadas, los artículos publicados para la venta, las preguntas recibidas, las calificaciones recibidas, la performance de sus publicaciones y el dinero transaccionado por el Usuario en su cuenta de Mercadolibre®, entre otras posibles. La Plataforma brinda al Usuario información pública sobre el estado de las ventas y de las publicaciones de determinados vendedores que compiten en el mercado del Usuario en Mercadolibre®.<br /><br /></p>
          <p><strong>4. Acceso a la Plataforma.<br /></strong><br/></p>
          <p>4.1. Los servicios de la Plataforma se ofrecen bajo la modalidad paga de suscripción mensual de acuerdo a las tarifas publicadas en la Plataforma.<br /><br /></p>
          <p>4.2. No obstante lo establecido en la cláusula 4.1. de las presentes Condiciones, SPIRAL podrá habilitar períodos de prueba, con o sin limitaciones de funcionalidades, en los que se permitirá utilizar al Usuario sin cargo la Plataforma durante algunos días corridos. Al finalizar el plazo de prueba, para seguir utilizando la Plataforma y acceder a su información, deberá contratar la modalidad paga de suscripción mensual.<br /><br /></p>
          <p>4.3. Para acceder a los servicios de la Plataforma -sin perjuicio de lo previsto en la cláusula 4.2.-, Usted deberá acreditar el pago de la suscripción mensual a la tarifa establecida o planes promocionales que de tanto en tanto sean ofrecidos por SPIRAL a los Usuarios, mediante el medio de pago seleccionado y términos y condiciones aplicables. Los pagos deben realizarse a mes adelantado. SPIRAL se reserva la facultad de modificar, a su exclusivo criterio, los precios publicados en la Plataforma así como la denominación, la clasificación, los requisitos y las funcionalidades de cada variante de los servicios correspondientes a cada precio publicado. La tarifa aplicable al pago de cada suscripción mensual será la tarifa contenida en el Cupón de Pago que SPIRAL remita al Usuario conforme lo previsto en la cláusula 4.4. de estas Condiciones que se mantendrá en vigencia por un plazo de 30 días. Vencido dicho plazo, la tarifa del Cupón de Pago pendiente será la tarifa aplicable a la tarifa del mes en curso.<br /><br /></p>
          <p>4.4. Medios de pago. SPIRAL acepta todo medio de pago aceptado por MercadoPago.<br />Usted se compromete a pagar a SPIRAL todos los gastos por los servicios contratados a SPIRAL mediante el uso de la Plataforma. El Usuario recibirá todos los meses un cupón de pago con una antelación de diez (10) días corridos al vencimiento de su suscripción mensual (o vencimiento de su período de prueba, en caso que corresponda), en adelante el "Cupón de Pago". En caso que el Usuario no abone el Cupón de Pago al vencimiento de su suscripción mensual, no podrá acceder a los servicios arancelados hasta tanto regularice su situación.<br /><br /></p>
          <p>4.5. La servicios arancelados estarán disponibles para Usted desde el momento en que SPIRAL verifique el pago efectuado por el Usuario. En caso que el pago no pueda ser verificado por SPIRAL, por cualquier motivo, SPIRAL podrá, a su exclusiva discreción, decidir la no habilitación a los servicios arancelados para el período imputado a ese pago, hasta tanto SPIRAL pueda verificar el pago realizado por el Usuario. En caso de no verificación del pago, SPIRAL le notificará al Usuario por correo electrónico esta situación.<br /><br /></p>
          <p>4.6. Los pagos realizados por el Usuario a SPIRAL no son reembolsables en ningún caso, tanto si la provisión del servicio es cancelada o terminada por el Usuario o por SPIRAL, por cualquier razón o causa.<br /><br /></p>
          <p><strong>5. Limitaciones al acceso y al uso de la Plataforma.<br /></strong><br/></p>
          <p>5.1. De acuerdo con los términos establecidos en las presentes Condiciones, SPIRAL otorga al Usuario durante el plazo correspondiente una licencia limitada, no exclusiva, no sublicenciable e intransferible para acceder y hacer uso de la Plataforma en la medida permitida en las presentes Condiciones. Todos los derechos que no se conceden expresamente en las presentes Condiciones están reservados por SPIRAL.<br /.<br /><br /></p>
          <p>5.2. El Usuario no podrá hacer ningún uso de la Plataforma que no esté expresamente permitido en las presentes Condiciones.<br /><br /></p>
          <p>5.3. Excepto que se indique expresamente lo contrario en estas Condiciones, el Usuario no podrá: (a) descargar, usar, copiar, crear trabajos derivados, o modificar la Plataforma o cualquier parte de la misma, (b) transferir, sublicenciar, arrendar, prestar, alquilar o distribuir la Plataforma a cualquier otra persona o entidad, o (c) usar la Plataforma de manera ilegal, para cualquier fin ilegal, o de cualquier manera no reconocida expresamente en las presentes Condiciones.<br /><br /></p>
          <p>5.4. SPIRAL se reserva el derecho exclusivo, a su solo criterio, de: (a) determinar las funciones, servicios, productos, software u otras herramientas que estarán disponibles para el uso del Usuario a través del Sitio y/o de la Plataforma, y (b) agregar, modificar o eliminar cualquier contenido, material y/o funcionalidad que esté disponible en la Plataforma y/o en el Sitio en cualquier momento y por cualquier razón. En este sentido, SPIRAL puede realizar actualizaciones, nuevas versiones, agregar nuevas funcionalidades y mejoras a la Plataforma y/o al Sitio.<br /><br /></p>
          <p>5.5. SPIRAL podrá permitirle el uso de la Plataforma y/o del Sitio, siempre y cuando: (I) Ud. no copie, distribuya o modifique ninguna parte de la Plataforma ni del Sitio sin previa autorización por escrito de SPIRAL; (II) Ud. no envíe spam, publicidad, correo no deseado, cadenas, etc.; (III) Ud. no transmita ningún contenido que incluya virus de software u otros programas, códigos o archivos que puedan dañar computadoras; (IV) Ud. no desconecte o interrumpa servidores o redes conectados al Sitio; y (V) Ud. cumpla con estas Condiciones. Ud. presta su acuerdo a no usar o lanzar cualquier sistema automatizado, incluyendo sin limitación "robots," "spiders" o "lectores offline", que acceden a la Plataforma y/o al Sitio de una manera que puedan mandar más mensajes de pedido a los servidores de SPIRAL durante un período dado de tiempo que los que un ser humano podría producir razonablemente durante el mismo período utilizando un buscador de web online convencional. SPIRAL permite a los operadores de motores públicos de búsqueda el uso de "spiders" para copiar materiales del Sitio y/o de la Plataforma con el único propósito de crear índices de materias ubicables, disponibles y pasibles de ser encontrados, pero no  'cachés'; o archivos de dichos materiales. SPIRAL se reserva el derecho de revocar estas excepciones tanto en general como en casos específicos. Ud. presta su acuerdo respecto de no colectar o almacenar cualquier información de identidad personal, incluyendo nombres de cuentas o direcciones correo electrónico del Sitio y/o de la Plataforma, ni de usar los sistemas de comunicaciones provistos por el Sitio y/o por la Plataforma para cualquier finalidad comercial que exceda el alcance específicamente y expresamente determinado en estas Condiciones.<br /><br /></p>
          <p>5.6. Cuentas de Usuario. Operadores. Responsabilidad Personal del Usuario. Para poder tener acceso a la Plataforma, Ud. deberá acceder a su Cuenta de Usuario de la Plataforma de SPIRAL (la "Cuenta de Usuario") a través de su cuenta de usuario de Mercadolibre®, En ningún momento SPIRAL podrá acceder, almacenar, utilizar ni conocer la contraseña de su cuenta de usuario de Mercadolibre®. Usted no podrá utilizar de ninguna manera una Cuenta de Usuario que pertenezca a otra persona, sin autorización expresa y por escrito del Usuario correspondiente., Un Usuario podrá autorizar a terceras personas a operar su Cuenta de Usuario como "Operador" con el alcance que determine ese Usuario. Cada Usuario titular de una Cuenta de Usuario en SPIRAL es responsable ante SPIRAL por la actividad de todos y cualquiera de los Operadores de su Cuenta de Usuario de SPIRAL que hayan sido autorizados para desempeñar algunas o todas las funciones que provee la Plataforma. Cada Operador acepta estas Condiciones y las Políticas de Privacidad al ingresar y usar la Plataforma como Operador, en base a la contraseña de Operador vinculada a una Cuenta de Usuario. Cada Usuario será el único responsable de toda la actividad que tenga lugar en su Cuenta de Usuario, y deberá mantener su contraseña protegida y segura. Si Ud. crea una Cuenta de Usuario en nombre de una persona jurídica, Ud. garantiza que tiene la autoridad para obligar a dicha entidad jurídica y que su aceptación de estas Condiciones se considerará como la aceptación por dicha persona jurídica. Cualquier brecha de seguridad o uso indebido que se produzcan en su Cuenta de Usuario deberán ser notificados de inmediato a SPIRAL. Ud. será el único responsable por cualquier uso que se haga de su Cuenta de Usuario o de su contraseña de acceso a la Cuenta de Usuario y de las pérdidas de SPIRAL u otros debido a dicho uso no autorizado. SPIRAL no se hará responsable por sus pérdidas o daños o por pérdidas o daños de terceros a causa de cualquier uso indebido o no autorizado de su Cuenta de Usuario.<br /><br /></p>
          <p>5.7. Cuentas de Usuario. Para utilizar la Plataforma, Ud. deberá crear una Cuenta de Usuario de SPIRAL, a la que accederá a través de su cuenta de usuario de Mercadolibre®, autorizando a SPIRAL a acceder y gestionar su información pública y privada de usuario de Mercadolibre® en los términos y condiciones que permite Mercadolibre® a través de su API y de acuerdo a lo previsto en estas Condiciones.<br /><br /></p>
          <p>5.8. Cancelación del acceso al Sitio y de Cuentas de Usuario. SPIRAL, a su sola discreción, tiene el derecho de cancelar su acceso al Sitio y/o a la Plataforma y de impedirle su uso de inmediato, así como de cancelar y/o suspender su Cuenta de Usuario, con y sin causa.<br /.<br /><br /></p>
          <p>5.9. Prohibiciones. Usted no puede acceder o utilizar la Plataforma y/o el Sitio para cualquier otro fin distinto del específicamente establecido en estas Condiciones. Usted acepta que, entre las actividades prohibidas, están incluidas (pero no limitadas a) las siguientes: a. Actividad delictiva o que viole las leyes aplicables de cualquier modo. b. La recopilación de datos o de cualquier contenido de la Plataforma para crear cualquier compilación o base de datos, sin el permiso escrito de SPIRAL. c. Engañar o defraudar a la compañía o a otros Usuarios de la Plataforma de cualquier modo y, en particular, con el objeto de obtener información confidencial. d. Hacer uso indebido de los servicios de soporte que provee SPIRAL o presentar falsas denuncias. e. Utilizar cualquier información obtenida a través de la Plataforma y/o del Sitio con el fin de acosar, molestar, abusar o dañar a terceros. f. Utilizar la Plataforma de cualquier modo con el propósito de competir con SPIRAL. g. Descifrar, decompilar, desensamblar o utilizar ingeniería inversa sobre cualquier software o código que conforma la Plataforma y/o el Sitio, o permitir o autorizar a cualquier otra persona o entidad para hacerlo. h. Eludir de cualquier modo cualquier medida diseñada para impedir o restringir el acceso a la Plataforma y/o al Sitio.<br /><br /></p>
          <p><strong>6. Contenidos proporcionados por Usted.<br /></strong><br/></p>
          <p>6.1. La Plataforma puede permitir a los Usuarios subir determinada información a la Plataforma o al Sitio. En todos los casos, Usted afirma y garantiza a SPIRAL que:<br /><br />a. Usted es el creador y propietario, o tiene las licencias necesarias, derechos, consentimientos, permisos para divulgar y/o permisos para utilizar los contenidos que ingrese en la Plataforma o en el Sitio;<br />b. Los contenidos que Usted ingrese a la Plataforma o al Sitio no violan o enlazan a material que viole cualquier disposición de estas Condiciones o de cualquier ley o reglamentación aplicable.<br /><br /></p>
          <p>6.2. Usted reconoce y acepta que cualquier pregunta, consulta, comentario, sugerencia, idea, u otra información sobre el Sitio o la Plataforma (en adelante, las "Contribuciones") aportadas por Usted a SPIRAL no son confidenciales y que SPIRAL (así como cualquier persona designada por ésta) tendrá derecho a la libre utilización y difusión de esas contribuciones para cualquier propósito, comercial o de otro tipo, sin su consentimiento ni asentimiento y sin compensación alguna para Usted.<br /><br /></p>
          <p>6.3. Usted declara y garantiza a SPIRAL que es el único responsable de adquirir u obtener el equipo informático y el software adecuado para utilizar de cualquier modo la Plataforma, y también declara y garantiza a SPIRAL que Usted será el único responsable por cualquier daño o pérdida que Usted sufra o pudiere sufrir como resultado de operar dichos equipos informáticos y software, incluyendo incompatibilidades entre la Plataforma y cualquier sistema operativo.<br /><br /></p>
          <p><strong>7. Derechos de Propiedad Intelectual.<br /></strong><br/></p>
          <p>7.1. Todos los contenidos del Sitio y de la Plataforma -incluyendo aunque no limitándose al texto, los documentos, las descripciones, los productos, el software, el código, gráficos, diseño, fotografía, sonido, videos, funciones interactivas, servicios, compilación de datos y ordenamiento de datos, y todo otro contenido en el Sitio y en la Plataforma- en adelante, el "Contenido", y las marcas registradas, marcas de servicio y logos incluidos en el Sitio y en la Plataforma ("marcas"), son propiedad de SPIRAL o están licenciados a SPIRAL.<br /.<br /><br /></p>
          <p>El Contenido que se le proporciona es para su uso personal únicamente y no podrá ser utilizado, copiado, distribuido, transmitido, emitido, desplegado, vendido, licenciado, descompilado o explotado para cualquier otro propósito sin el consentimiento previo y por escrito de SPIRAL. SPIRAL se reserva todos los derechos que no estén expresamente otorgados a Usted en la Plataforma o en el Sitio. Si Ud. descarga o imprime una copia del Contenido para su uso personal, deberá retener todos los derechos reservados y otros avisos propietarios que allí se encuentren.<br /><br /></p>
          <p><strong>8. Confidencialidad.<br /></strong><br/></p>
          <p>8.1. En el marco de la provisión de los servicios descriptos en estas Condiciones, Usted podría tener acceso a cierta información propietaria, confidencial y/o secreto comercial de SPIRAL, tanto oralmente como por escrito, o por cualquier otro medio (en adelante, la "Información Confidencial").<br /><br /></p>
          <p>8.2. El Usuario acepta no divulgar la Información Confidencial de SPIRAL a terceros, no utilizar la Información Confidencial de SPIRAL para fines que no sean exclusivamente el cumplimiento de las presentes Condiciones, y mantener la confidencialidad de la Información Confidencial de SPIRAL aplicando el mismo nivel de cuidado que el que el Usuario utiliza para proteger su propia Información Confidencial, que en todo caso no podrá ser inferior a un grado razonable de cuidado.<br /.<br /><br /></p>
          <p><strong>9. Vínculos. Sitios web de terceros.<br /></strong><br/></p>
          <p>9.1. El Sitio contiene vínculos a sitios web de terceras partes que no son propiedad ni están controlados por SPIRAL. SPIRAL no está vinculada a estos sitios web, no tiene control sobre estos sitios web y no asume responsabilidad alguna por el contenido, las políticas de privacidad o las prácticas de cualquier sitio web en calidad de terceras partes.<br /><br /></p>
          <p>Por medio del uso del Sitio y/o de la Plataforma, Ud. libera expresamente a SPIRAL de toda y cualquier responsabilidad que pueda surgir de su uso de cualquier sitio web como tercera parte. De acuerdo a ello, le recordamos que esté atento a que, cuando deje el Sitio y/o la Plataforma, lea los términos y las condiciones y la política de privacidad de cada uno de los sitios que visite.<br /><br /></p>
          <p>9.2. En particular, usted acepta y reconoce que los servicios provistos por los sitios de Mercadolibre® y sus variantes regionales son provistos por terceros, ajenos a SPIRAL. La Plataforma permite la integración con ciertos servicios de Mercadolibre® mediante un una interfaz de comunicación (API), para la gestión y administración de publicaciones de productos o servicios para la venta en Mercadolibre®. Usted reconoce y acepta regirse por las condiciones de servicio de Mercadolibre® por cualquier consecuencia legal, incluyendo posibles costos de servicio, generada en forma directa o indirecta mediante su uso de la Plataforma para la gestión y administración de publicaciones de productos o servicios para la venta en Mercadolibre®. En ningún caso SPIRAL responderá por fallas e inconsistencias u otros de la API o de los sitios de Mercadolibre®.<br /><br /></p>
          <p>9.3. La inclusión, vinculación, el uso o acceso a cualquier sitio de terceros o de desde la Plataforma no implica en modo alguno la aprobación o respaldo de dicho sitio o contenido por parte de SPIRAL.<br /><br /></p>
          <p><strong>10. Descripción de la Información.<br /></strong><br/></p>
          <p>SPIRAL trata de mantener la mayor exactitud posible en el Sitio y en la Plataforma. Sin embargo, SPIRAL no puede garantizar ni garantiza que el contenido disponible en el Sitio y/o en la Plataforma sea exacto, completo, seguro o libre de errores. En particular, SPIRAL no puede garantizar ni garantiza que la información provista al Usuario en la provisión de los servicios descriptos en la cláusula 3 de estas Condiciones sea exacto, completo, seguro o libre de errores. SPIRAL se reserva el derecho de efectuar cambios en o al contenido, o a cualquiera de sus partes, de acuerdo a su solo juicio y sin la obligación de dar aviso alguno a los usuarios antes o después de efectuar tales cambios a dichos contenidos.<br /><br /></p>
          <p><strong>11. Privacidad<br /></strong><br/></p>
          <p>11.1. Nos preocupamos por su privacidad. Por favor, revise las Políticas de Privacidad de SPIRAL. Al utilizar el Sitio Web o la Plataforma, Usted acepta los términos de las Políticas de Privacidad de SPIRAL.<br /><br /></p>
          <p>11.2. La gestión y la provisión de los servicios provistos por SPIRAL requiere el tratamiento por parte de SPIRAL de múltiples datos que constituyen información pública provista por los Usuarios y por terceros a SPIRAL y/o a sitios web de terceros, como www.mercadolibre.com o demás sitios de Mercadolibre®. Estos datos serán tratados de acuerdo a lo establecido en la normativa vigente aplicable en materia de datos de carácter personal y conforme a lo dispuesto en nuestra Política de Privacidad.<br /><br /></p>
          <p><strong>12. Duración y finalización del acuerdo de servicios.<br /></strong><br/></p>
          <p>12.1. Si Usted es Usuario, su acuerdo con SPIRAL permanecerá en plena vigencia y producirá todos sus efectos legales mientras usted efectúe los pagos de acuerdo con lo dispuesto en la cláusula 4 de estas Condiciones. Usted puede terminar su uso o su participación en la Plataforma en cualquier momento y por cualquier motivo, siguiendo siempre las instrucciones para la baja de Cuentas de Usuario que se encuentra en la configuración de su Cuenta de Usuario, teniendo en cuenta que los montos ya pagados no serán reembolsables, según lo dispuesto en estas Condiciones.<br /><br /></p>
          <p>12.2. Si el acuerdo es terminado por la falta de cobro por parte de SPIRAL de acuerdo con lo dispuesto en la cláusula 4 de estas Condiciones por cualquier motivo, todos sus datos e información histórica por el uso de la Plataforma permanecerán almacenados por el plazo previsto más abajo y podrá acceder a ellos una vez que su cuenta sea reactivada por SPIRAL, previa acreditación de los pagos correspondientes. Sus datos e información permanecerán disponibles por un período de dos (2) meses desde la terminación de la provisión del servicio por falta de cobro. Una vez vencido dicho plazo de dos meses, los datos e información del Usuario dado de baja que se hubiere acumulado en la Plataforma será eliminada de la base de datos de SPIRAL y no podrá ser recuperada por el Usuario en ningún caso y bajo ninguna circunstancia, sin responsabilidad alguna por parte de SPIRAL.<br /><br /></p>
          <p><strong>13. Modificaciones a la Plataforma.<br /></strong><br/></p>
          <p>13.1. SPIRAL se reserva el derecho de, en cualquier momento, modificar o discontinuar, temporal o permanentemente, la Plataforma (o cualquier parte de la misma) con o sin previo aviso. Usted acepta que SPIRAL no será responsable ante usted ni ante ningún tercero por cualquier modificación, suspensión o interrupción definitiva de la Plataforma.<br /><br /></p>
          <p><strong>14. Limitación general de responsabilidad y garantía.<br /></strong><br/></p>
          <p>SPIRAL no garantiza que el sitio esté libre de errores, ataques de virus, o que siempre estará disponible. El sitio en ocasiones estará inaccesible debido a mantenimientos, actualizaciones o por otros motivos.<br /><br /></p>
          <p>SPIRAL no será responsable por el extravío de bienes, dinero, daños de reputación o consecuencias que resulten del uso, o de la imposibilidad de dicho uso y de sus servicios.<br /><br /></p>
          <p>UD acuerda que SPIRAL no se hará responsable por ninguna consecuencia para con sus usuarios que podrían surgir a causa de problemas técnicos de internet, lentitud en conexiones, etc.<br /><br /></p>
          <p>SPIRAL no garantiza, promociona o asegura ningún contenido, producto o servicio que aparezca publicado en el sitio.<br /><br /></p>
          <p><strong>15. Generalidades.<br /></strong><br/></p>
          <p>15.1. En caso de que un tribunal o autoridad judicial o administrativa declare la nulidad de una o más cláusulas de las presentes Condiciones, tal nulidad no afectará el resto de las estipulaciones, las que subsistirán y producirán respecto de las partes todos los efectos por ellas deseados.<br /><br /></p>
          <p>15.2. Si alguna cláusula de las presentes Condiciones fuera declarada nula, el Visitante o Usuario involucrado y SPIRAL harán sus mejores esfuerzos para sustituir o modificar la cláusula respetando el espíritu de la presente.<br /><br /></p>
          <p>15.3. Cualquier controversia que se suscite en torno a la existencia, validez, interpretación o cumplimiento de la presente será sometida a resolución de los Tribunales Ordinarios en lo Comercial de la Capital Federal, Argentina, con renuncia a cualquier otro fuero o jurisdicción que pudiera corresponderles.<br /><br /></p>
          <p>15.4. Salvo que se indique lo contrario, cualquier notificación hacia SPIRAL deberá realizarse por medio de correo electrónico a la dirección de correo electrónico contacto@spiral.com.<br /><br /></p>
          <p>15.5. Todas las comunicaciones dirigidas a Usted serán dirigidas a la dirección de correo electrónico que proporcionó durante el proceso de registro.<br /><br /></p>
          <p>15.6. A los efectos de estas Condiciones, las notificaciones que haga SPIRAL por medio de correo electrónico se considerarán como recibidas, leídas y aceptadas 24 horas después de enviado dicho correo, a menos que la SPIRAL sea expresamente anoticiado de que la dirección de correo electrónico es inválida o de que el correo electrónico no ha llegado a destino.<br /><br /></p>
          <p>15.7. Estas Condiciones, con el alcance establecido en estas Condiciones, constituye el acuerdo completo entre Usted y SPIRAL con respecto al uso del Sitio y de la Plataforma.<br /><br /></p>
        </div>
      </div>
    </section>

    <?php include("includes/footer.inc.php"); ?>
  </div>
  <!-- footer -->
  <?php include("includes/scripts.inc.html"); ?>
</body>

</html>